//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vancl.IC.VWS.ClientService.FileWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="VwsDirectoryInfoList", Namespace="http://schemas.datacontract.org/2004/07/Vancl.IC.VWS.ClientService.Model", ItemName="VwsDirectoryInfo")]
    [System.SerializableAttribute()]
    public class VwsDirectoryInfoList : System.Collections.Generic.List<Vancl.IC.VWS.ClientService.Model.VwsDirectoryInfo> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileWCF.IFileTransService")]
    public interface IFileTransService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransService/Download", ReplyAction="http://tempuri.org/IFileTransService/DownloadResponse")]
        byte[] Download(out string md5, string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransService/Upload", ReplyAction="http://tempuri.org/IFileTransService/UploadResponse")]
        bool Upload(byte[] fileBytes, string md5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransService/GetFileList", ReplyAction="http://tempuri.org/IFileTransService/GetFileListResponse")]
        Vancl.IC.VWS.ClientService.FileWCF.VwsDirectoryInfoList GetFileList(string folderPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileTransServiceChannel : Vancl.IC.VWS.ClientService.FileWCF.IFileTransService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransServiceClient : System.ServiceModel.ClientBase<Vancl.IC.VWS.ClientService.FileWCF.IFileTransService>, Vancl.IC.VWS.ClientService.FileWCF.IFileTransService {
        
        public FileTransServiceClient() {
        }
        
        public FileTransServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] Download(out string md5, string filePath) {
            return base.Channel.Download(out md5, filePath);
        }
        
        public bool Upload(byte[] fileBytes, string md5) {
            return base.Channel.Upload(fileBytes, md5);
        }
        
        public Vancl.IC.VWS.ClientService.FileWCF.VwsDirectoryInfoList GetFileList(string folderPath) {
            return base.Channel.GetFileList(folderPath);
        }
    }
}
